name: init

on:
  create:
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v2
      - run: echo "New file" > NEW.txt
      - run: sed -i "s/bach-library-template/${{ github.event.repository.name }}/g" README.md
      - run: rm .github/workflows/init.yml
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com      
          git add .
          git commit -m "Initial adjustment"
          git push origin main
