name: init

on:
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v2
      - run: |
          USER=${{ github.event.repository.owner.login }}
          REPO=${{ github.event.repository.name }}
          rename .idea/bach-library-template.iml .idea/$REPO.iml
          rename .idea/com.github.sormuras.library.iml .idea/com.github.$USER.$REPO.iml
          rename com.github.sormuras.library/main/java/com/github/sormuras/library com.github.sormuras.library/main/java/com/github/$USER/$REPO
          rename com.github.sormuras.library com.github.$USER.$REPO
          find ./ -type f -exec sed -i 's/bach-library-template/$REPO/g' {} \;
          find ./ -type f -exec sed -i 's/com.github.sormuras.library/com.github.$USER.$REPO/g' {} \;
          rm .github/workflows/init.yml
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com      
          git add .
          git commit -m "Adjust names"
          git push origin main
