name: init

on:
  create:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v2
      - run: echo "New file" > NEW.txt
      - run: sed "s/bach-library-template/${{ github.event.repository.name }}/g" README.md
      - run: rm .github/workflows/init.yml
      - run: |
          git add .
          git commit -m "Initialized"
          git push origin main
